### PR TITLE
Project mavenization

### PR DESCRIPTION
**Pull request by fpompermaier**
Here it is :+1:

### CODE REVIEW

**Comment by milg0** [comment]
Too many changes to overview and your code is not usable (it works with your local paths, e.g. wsdlLocation = "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver10/device/wsdl/devicemgmt.wsdl").

The code is without any documentation and not maintainable. It replaces my complete code, so it's not compatible to old code.

And I must admit, I don't understand your use of the wsdl files.

Your WS Discovery does use the ip address 239.255.255.250, where does that ip come from? You have also set a default configuration for the user "admin", not every device with an admin-user does work with your password. You are not supporting any error handeling.

Your code makes the code more complicated for newbies, not easier.

Supporting maven is a good idea and there are also reasons for a more flexible code. But the code must be working, readable and maintainable. I don't even see a reason for you to send a pull request, you just kept two classes and you did change one of these a lot.

**Comment by fpompermaier** [comment]
First of all, let's make myself clear: I just wanted to help other people willing to approach ONVIF standard with Java. At the moment, your library is the best one I found around and I think that you did a good job. You told me to make a PR in a conversation we had throug email, that was not my inital idea (indeed I deleted a brand new github repository I've created).

Of course before making the PR I didn't pay enough attention to the details (like configurable password and wsdl location). The WS Discovery is a module I kept for backward compatibility with your dependecies but I don't care about it. That address comes from https://github.com/thhart/javaWsDiscovery/blob/master/src/org/me/javawsdiscovery/DeviceDiscovery.java. 

The other things you said are just bullshits...do you really think your code is more maintainable????
What if I want to connect to the event service? I have to go throug the ONVIF specs and write manually the entire service!!! Like you did for the services in onvif-java-lib/src/de/onvif/soap/devices.

**Comment by milg0** [comment]
At least you don't take it personally. I didn't want to offend you.

No, my code isn't maintainable, but I know how it works and I can work with it. And I give people a JAR archive and a tutorial how to work with that. It's not the best solution for everyone but it is one everybody can work with.
But I can't work with your code and others will have problems working with it. I created this repo to give others the chance to improve it (e.g. implement event service for everyone). Like someone did with DeviceDiscovery.

Well, if you don't want to get your code into my repo, I don't have any idea what you want from me. You are free to work on your own library, also I think it is everytime a good time to work on one good solutions instead of two. But it seems you don't want your code in this project, otherwise you would want a pull of your code. So now, what do you want me to do?

I can't replace my whole code with yours that isn't working, sorry for that. I think you can understand that. You're gladly invited to improve the code and to implement automatismns (e.g. you could create your own branch?) but the library still has to work afterwards because people all over the world work with it.

**Comment by fpompermaier** [comment]
You're right about the fact that the code should compile at least... I was just excited to share my brand new code with you that I didn't care about those trivial aspects..before issuing another PR I'll check those things, I'll promise. I don't know wheter you're a developer or not but from my point of view (as a developer) you're code cannot be considered in any professional solution: it's not possibile to regenerate the Java classes from the wsdl, it's not mavenized, it's not modular and, worst of all, the services has to be written by hand! That's not substainable.
My version is substantially divided in 2 modules: the real application and the Java stubs for the WS (plus the discovery service that I could even drop...before I could try to adjust it).
To call a service you just jave to use the client generated by the CXF mavenplugin and you have for free the list of available methods and required parameters . That's really a huge improvement for new users willing to interface with the system.
In particular, I wanted to interface with the Event part and using your code there was no alternative but creating an EventDevice from the scratch! Sorry but I'm a little bit radical/feticist about those things..I can't really waste my time that way!!

What I want for you? Nothing particular.. :)
I like opensource and contribute to it..since you did a good job and I think you have some passion about this thing I'd like to improve it. But if you're scared to make such a big step I can understand you. Of course it's good for users to have alternatives but this is not the spirit of open source: it's collaboration, discussion (as we're doing) but, in the end, satisfaction of course ;)

**Pull request closed without merging**
